<?php

namespace Database\Seeders\Catalogo;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Catálogo cerrado de división político-administrativa de Bolivia (adenda
 * 16/9/2026 a ADR 0018 punto 1): departamento → provincia → municipio,
 * reemplaza el texto libre que tenía `com_propiedades` desde HU-76.
 *
 * Datos: dump propio del dueño (otro sistema, `instituto_incos`), sin el
 * nivel país que tenía allá (acá no se modela país). Se conservan los IDs
 * originales del dump para que las FK encadenadas (`departamento_id` en
 * provincias, `provincia_id` en municipios) queden idénticas a la fuente,
 * sin remapeo. `localidad` NO tiene catálogo — sigue siendo texto libre en
 * `com_propiedades`, no hay datos de esa granularidad en el dump.
 *
 * Corre en todos los entornos, producción incluida — mismo criterio que
 * `ComercialCultivosSeeder`. `created_by`/`updated_by` NULL: dato de
 * catálogo, sin autor humano. Idempotente vía `insertOrIgnore` por PK
 * explícita: correrlo de nuevo no duplica ni pisa filas ya sembradas.
 */
class GeografiaBoliviaSeeder extends Seeder
{
    public function run(): void
    {
        $this->sembrarDepartamentos();
        $this->sembrarProvincias();
        $this->sembrarMunicipios();
    }

    private function sembrarDepartamentos(): void
    {
        $ahora = now();

        $filas = array_map(
            fn (array $fila) => $fila + ['created_at' => $ahora, 'updated_at' => $ahora],
            self::DEPARTAMENTOS,
        );

        foreach (array_chunk($filas, 200) as $lote) {
            DB::table('com_departamentos')->insertOrIgnore($lote);
        }
    }

    private function sembrarProvincias(): void
    {
        $ahora = now();

        $filas = array_map(
            fn (array $fila) => $fila + ['created_at' => $ahora, 'updated_at' => $ahora],
            self::PROVINCIAS,
        );

        foreach (array_chunk($filas, 200) as $lote) {
            DB::table('com_provincias')->insertOrIgnore($lote);
        }
    }

    private function sembrarMunicipios(): void
    {
        $ahora = now();

        $filas = array_map(
            fn (array $fila) => $fila + ['created_at' => $ahora, 'updated_at' => $ahora],
            self::MUNICIPIOS,
        );

        foreach (array_chunk($filas, 200) as $lote) {
            DB::table('com_municipios')->insertOrIgnore($lote);
        }
    }

    /** @var list<array{id: int, nombre: string}> */
    private const DEPARTAMENTOS = [
        ['id' => 1, 'nombre' => 'Santa Cruz'],
        ['id' => 2, 'nombre' => 'La Paz'],
        ['id' => 3, 'nombre' => 'Cochabamba'],
        ['id' => 4, 'nombre' => 'Potosí'],
        ['id' => 5, 'nombre' => 'Chuquisaca'],
        ['id' => 6, 'nombre' => 'Oruro'],
        ['id' => 7, 'nombre' => 'Tarija'],
        ['id' => 8, 'nombre' => 'Beni'],
        ['id' => 9, 'nombre' => 'Pando'],
    ];

    /** @var list<array{id: int, departamento_id: int, nombre: string}> */
    private const PROVINCIAS = [
        ['id' => 1, 'departamento_id' => 1, 'nombre' => 'Andrés Ibáñez'],
        ['id' => 2, 'departamento_id' => 1, 'nombre' => 'Ignacio Warnes'],
        ['id' => 3, 'departamento_id' => 1, 'nombre' => 'Obispo Santiestevan'],
        ['id' => 4, 'departamento_id' => 1, 'nombre' => 'Sara'],
        ['id' => 5, 'departamento_id' => 1, 'nombre' => 'Cordillera'],
        ['id' => 6, 'departamento_id' => 1, 'nombre' => 'Ichilo'],
        ['id' => 7, 'departamento_id' => 1, 'nombre' => 'Vallegrande'],
        ['id' => 8, 'departamento_id' => 1, 'nombre' => 'Manuel María Caballero'],
        ['id' => 9, 'departamento_id' => 1, 'nombre' => 'Ñuflo de Chávez'],
        ['id' => 10, 'departamento_id' => 1, 'nombre' => 'Guarayos'],
        ['id' => 11, 'departamento_id' => 1, 'nombre' => 'Chiquitos'],
        ['id' => 12, 'departamento_id' => 1, 'nombre' => 'José Miguel de Velasco'],
        ['id' => 13, 'departamento_id' => 1, 'nombre' => 'Germán Busch'],
        ['id' => 14, 'departamento_id' => 1, 'nombre' => 'Florida'],
        ['id' => 15, 'departamento_id' => 1, 'nombre' => 'Ángel Sandoval'],
        ['id' => 16, 'departamento_id' => 2, 'nombre' => 'Pedro Domingo Murillo'],
        ['id' => 17, 'departamento_id' => 2, 'nombre' => 'Los Andes'],
        ['id' => 18, 'departamento_id' => 2, 'nombre' => 'Ingavi'],
        ['id' => 19, 'departamento_id' => 2, 'nombre' => 'Aroma'],
        ['id' => 20, 'departamento_id' => 2, 'nombre' => 'Omasuyos'],
        ['id' => 21, 'departamento_id' => 2, 'nombre' => 'Gualberto Villarroel'],
        ['id' => 22, 'departamento_id' => 2, 'nombre' => 'Manco Kapac'],
        ['id' => 23, 'departamento_id' => 2, 'nombre' => 'Pacajes'],
        ['id' => 24, 'departamento_id' => 2, 'nombre' => 'Nor Yungas'],
        ['id' => 25, 'departamento_id' => 2, 'nombre' => 'Sud Yungas'],
        ['id' => 26, 'departamento_id' => 2, 'nombre' => 'Caranavi'],
        ['id' => 27, 'departamento_id' => 2, 'nombre' => 'Larecaja'],
        ['id' => 28, 'departamento_id' => 2, 'nombre' => 'Inquisivi'],
        ['id' => 29, 'departamento_id' => 2, 'nombre' => 'Loayza'],
        ['id' => 30, 'departamento_id' => 2, 'nombre' => 'José Manuel Pando'],
        ['id' => 31, 'departamento_id' => 2, 'nombre' => 'Muñecas'],
        ['id' => 32, 'departamento_id' => 2, 'nombre' => 'Eliodoro Camacho'],
        ['id' => 33, 'departamento_id' => 2, 'nombre' => 'Bautista Saavedra'],
        ['id' => 34, 'departamento_id' => 2, 'nombre' => 'Franz Tamayo'],
        ['id' => 35, 'departamento_id' => 2, 'nombre' => 'Abel Iturralde'],
        ['id' => 36, 'departamento_id' => 3, 'nombre' => 'Cercado'],
        ['id' => 37, 'departamento_id' => 3, 'nombre' => 'Quillacollo'],
        ['id' => 38, 'departamento_id' => 3, 'nombre' => 'Chapare'],
        ['id' => 39, 'departamento_id' => 3, 'nombre' => 'Punata'],
        ['id' => 40, 'departamento_id' => 3, 'nombre' => 'Tapacarí'],
        ['id' => 41, 'departamento_id' => 3, 'nombre' => 'Esteban Arze'],
        ['id' => 42, 'departamento_id' => 3, 'nombre' => 'Arani'],
        ['id' => 43, 'departamento_id' => 3, 'nombre' => 'Ayopaya'],
        ['id' => 44, 'departamento_id' => 3, 'nombre' => 'Capinota'],
        ['id' => 45, 'departamento_id' => 3, 'nombre' => 'Carrasco'],
        ['id' => 46, 'departamento_id' => 3, 'nombre' => 'Bolívar'],
        ['id' => 47, 'departamento_id' => 3, 'nombre' => 'Mizque'],
        ['id' => 48, 'departamento_id' => 3, 'nombre' => 'Campero'],
        ['id' => 49, 'departamento_id' => 3, 'nombre' => 'Tiraque'],
        ['id' => 50, 'departamento_id' => 3, 'nombre' => 'Germán Jordán'],
        ['id' => 51, 'departamento_id' => 3, 'nombre' => 'Arque'],
        ['id' => 52, 'departamento_id' => 4, 'nombre' => 'Tomás Frías'],
        ['id' => 53, 'departamento_id' => 4, 'nombre' => 'Nor Chichas'],
        ['id' => 54, 'departamento_id' => 4, 'nombre' => 'Modesto Omiste'],
        ['id' => 55, 'departamento_id' => 4, 'nombre' => 'Enrique Baldivieso'],
        ['id' => 56, 'departamento_id' => 4, 'nombre' => 'Rafael Bustillo'],
        ['id' => 57, 'departamento_id' => 4, 'nombre' => 'Antonio Quijarro'],
        ['id' => 58, 'departamento_id' => 4, 'nombre' => 'Sud Chichas'],
        ['id' => 59, 'departamento_id' => 4, 'nombre' => 'Cornelio Saavedra'],
        ['id' => 60, 'departamento_id' => 4, 'nombre' => 'José María Linares'],
        ['id' => 61, 'departamento_id' => 4, 'nombre' => 'Charcas'],
        ['id' => 62, 'departamento_id' => 4, 'nombre' => 'Chayanta'],
        ['id' => 63, 'departamento_id' => 4, 'nombre' => 'Nor Lípez'],
        ['id' => 64, 'departamento_id' => 4, 'nombre' => 'Sud Lípez'],
        ['id' => 65, 'departamento_id' => 4, 'nombre' => 'Alonso de Ibáñez'],
        ['id' => 66, 'departamento_id' => 4, 'nombre' => 'Bernardino Bilbao'],
        ['id' => 67, 'departamento_id' => 4, 'nombre' => 'Daniel Campos'],
        ['id' => 68, 'departamento_id' => 5, 'nombre' => 'Oropeza'],
        ['id' => 69, 'departamento_id' => 5, 'nombre' => 'Tomina'],
        ['id' => 70, 'departamento_id' => 5, 'nombre' => 'Azurduy'],
        ['id' => 71, 'departamento_id' => 5, 'nombre' => 'Jaime Zudáñez'],
        ['id' => 72, 'departamento_id' => 5, 'nombre' => 'Yamparáez'],
        ['id' => 73, 'departamento_id' => 5, 'nombre' => 'Hernando Siles'],
        ['id' => 74, 'departamento_id' => 5, 'nombre' => 'Nor Cinti'],
        ['id' => 75, 'departamento_id' => 5, 'nombre' => 'Sud Cinti'],
        ['id' => 76, 'departamento_id' => 5, 'nombre' => 'Belisario Boeto'],
        ['id' => 77, 'departamento_id' => 5, 'nombre' => 'Luis Calvo'],
        ['id' => 78, 'departamento_id' => 6, 'nombre' => 'Cercado'],
        ['id' => 79, 'departamento_id' => 6, 'nombre' => 'Poopó'],
        ['id' => 80, 'departamento_id' => 6, 'nombre' => 'Pantaleón Dalence'],
        ['id' => 81, 'departamento_id' => 6, 'nombre' => 'Saucarí'],
        ['id' => 82, 'departamento_id' => 6, 'nombre' => 'Sebastián Pagador'],
        ['id' => 83, 'departamento_id' => 6, 'nombre' => 'Tomas Barrón'],
        ['id' => 84, 'departamento_id' => 6, 'nombre' => 'Mejillones'],
        ['id' => 85, 'departamento_id' => 6, 'nombre' => 'San Pedro de Totora'],
        ['id' => 86, 'departamento_id' => 6, 'nombre' => 'Litoral'],
        ['id' => 87, 'departamento_id' => 6, 'nombre' => 'Eduardo Avaroa'],
        ['id' => 88, 'departamento_id' => 6, 'nombre' => 'Nor Carangas'],
        ['id' => 89, 'departamento_id' => 6, 'nombre' => 'Sud Carangas'],
        ['id' => 90, 'departamento_id' => 6, 'nombre' => 'Carangas'],
        ['id' => 91, 'departamento_id' => 6, 'nombre' => 'Sajama'],
        ['id' => 92, 'departamento_id' => 6, 'nombre' => 'Ladislao Cabrera'],
        ['id' => 93, 'departamento_id' => 6, 'nombre' => 'Atahuallpa'],
        ['id' => 94, 'departamento_id' => 7, 'nombre' => 'Cercado'],
        ['id' => 95, 'departamento_id' => 7, 'nombre' => 'Eustaquio Méndez'],
        ['id' => 96, 'departamento_id' => 7, 'nombre' => 'José María Avilés'],
        ['id' => 97, 'departamento_id' => 7, 'nombre' => 'Aniceto Arce'],
        ['id' => 98, 'departamento_id' => 7, 'nombre' => 'Burnet O\'Connor'],
        ['id' => 99, 'departamento_id' => 7, 'nombre' => 'Gran Chaco'],
        ['id' => 100, 'departamento_id' => 8, 'nombre' => 'Cercado'],
        ['id' => 101, 'departamento_id' => 8, 'nombre' => 'Yacuma'],
        ['id' => 102, 'departamento_id' => 8, 'nombre' => 'Vaca Díez'],
        ['id' => 103, 'departamento_id' => 8, 'nombre' => 'Mamoré'],
        ['id' => 104, 'departamento_id' => 8, 'nombre' => 'Moxos'],
        ['id' => 105, 'departamento_id' => 8, 'nombre' => 'Marbán'],
        ['id' => 106, 'departamento_id' => 8, 'nombre' => 'José Ballivián'],
        ['id' => 107, 'departamento_id' => 8, 'nombre' => 'Iténez'],
        ['id' => 108, 'departamento_id' => 9, 'nombre' => 'Nicolás Suárez'],
        ['id' => 109, 'departamento_id' => 9, 'nombre' => 'Manuripi'],
        ['id' => 110, 'departamento_id' => 9, 'nombre' => 'Madre de Dios'],
        ['id' => 111, 'departamento_id' => 9, 'nombre' => 'Federico Román'],
        ['id' => 112, 'departamento_id' => 9, 'nombre' => 'Abuná'],
    ];

    /** @var list<array{id: int, provincia_id: int, nombre: string}> */
    private const MUNICIPIOS = [
        ['id' => 1, 'provincia_id' => 1, 'nombre' => 'Santa Cruz de la Sierra'],
        ['id' => 2, 'provincia_id' => 1, 'nombre' => 'Cotoca'],
        ['id' => 3, 'provincia_id' => 1, 'nombre' => 'Porongo'],
        ['id' => 4, 'provincia_id' => 1, 'nombre' => 'La Guardia'],
        ['id' => 5, 'provincia_id' => 1, 'nombre' => 'El Torno'],
        ['id' => 6, 'provincia_id' => 2, 'nombre' => 'Warnes'],
        ['id' => 7, 'provincia_id' => 2, 'nombre' => 'Okinawa Uno'],
        ['id' => 8, 'provincia_id' => 3, 'nombre' => 'Montero'],
        ['id' => 9, 'provincia_id' => 3, 'nombre' => 'General Saavedra'],
        ['id' => 10, 'provincia_id' => 3, 'nombre' => 'Mineros'],
        ['id' => 11, 'provincia_id' => 3, 'nombre' => 'Fernández Alonso'],
        ['id' => 12, 'provincia_id' => 3, 'nombre' => 'San Pedro'],
        ['id' => 13, 'provincia_id' => 4, 'nombre' => 'Portachuelo'],
        ['id' => 14, 'provincia_id' => 4, 'nombre' => 'Santa Rosa del Sara'],
        ['id' => 15, 'provincia_id' => 4, 'nombre' => 'Colpa Bélgica'],
        ['id' => 16, 'provincia_id' => 5, 'nombre' => 'Lagunillas'],
        ['id' => 17, 'provincia_id' => 5, 'nombre' => 'Charagua'],
        ['id' => 18, 'provincia_id' => 5, 'nombre' => 'Cabezas'],
        ['id' => 19, 'provincia_id' => 5, 'nombre' => 'Cuevo'],
        ['id' => 20, 'provincia_id' => 5, 'nombre' => 'Gutiérrez'],
        ['id' => 21, 'provincia_id' => 5, 'nombre' => 'Camiri'],
        ['id' => 22, 'provincia_id' => 5, 'nombre' => 'Boyuibe'],
        ['id' => 23, 'provincia_id' => 6, 'nombre' => 'Buena Vista'],
        ['id' => 24, 'provincia_id' => 6, 'nombre' => 'San Carlos'],
        ['id' => 25, 'provincia_id' => 6, 'nombre' => 'Yapacaní'],
        ['id' => 26, 'provincia_id' => 6, 'nombre' => 'San Juan de Yapacaní'],
        ['id' => 27, 'provincia_id' => 7, 'nombre' => 'Vallegrande'],
        ['id' => 28, 'provincia_id' => 7, 'nombre' => 'Trigal'],
        ['id' => 29, 'provincia_id' => 7, 'nombre' => 'Moro Moro'],
        ['id' => 30, 'provincia_id' => 7, 'nombre' => 'Postrer Valle'],
        ['id' => 31, 'provincia_id' => 7, 'nombre' => 'Pucará'],
        ['id' => 32, 'provincia_id' => 8, 'nombre' => 'Comarapa'],
        ['id' => 33, 'provincia_id' => 8, 'nombre' => 'Saipina'],
        ['id' => 34, 'provincia_id' => 9, 'nombre' => 'Concepción'],
        ['id' => 35, 'provincia_id' => 9, 'nombre' => 'San Javier'],
        ['id' => 36, 'provincia_id' => 9, 'nombre' => 'San Ramón'],
        ['id' => 37, 'provincia_id' => 9, 'nombre' => 'San Julián'],
        ['id' => 38, 'provincia_id' => 9, 'nombre' => 'San Antonio de Lomerío'],
        ['id' => 39, 'provincia_id' => 9, 'nombre' => 'Cuatro Cañadas'],
        ['id' => 40, 'provincia_id' => 10, 'nombre' => 'Ascensión de Guarayos'],
        ['id' => 41, 'provincia_id' => 10, 'nombre' => 'Urubichá'],
        ['id' => 42, 'provincia_id' => 10, 'nombre' => 'El Puente'],
        ['id' => 43, 'provincia_id' => 11, 'nombre' => 'San José de Chiquitos'],
        ['id' => 44, 'provincia_id' => 11, 'nombre' => 'Pailón'],
        ['id' => 45, 'provincia_id' => 11, 'nombre' => 'Roboré'],
        ['id' => 46, 'provincia_id' => 12, 'nombre' => 'San Ignacio de Velasco'],
        ['id' => 47, 'provincia_id' => 12, 'nombre' => 'San Miguel de Velasco'],
        ['id' => 48, 'provincia_id' => 12, 'nombre' => 'San Rafael'],
        ['id' => 49, 'provincia_id' => 13, 'nombre' => 'Puerto Suárez'],
        ['id' => 50, 'provincia_id' => 13, 'nombre' => 'Puerto Quijarro'],
        ['id' => 51, 'provincia_id' => 13, 'nombre' => 'El Carmen Rivero Tórrez'],
        ['id' => 52, 'provincia_id' => 14, 'nombre' => 'Samaipata'],
        ['id' => 53, 'provincia_id' => 14, 'nombre' => 'Pampa Grande'],
        ['id' => 54, 'provincia_id' => 14, 'nombre' => 'Mairana'],
        ['id' => 55, 'provincia_id' => 14, 'nombre' => 'Quirusillas'],
        ['id' => 56, 'provincia_id' => 15, 'nombre' => 'San Matías'],
        ['id' => 57, 'provincia_id' => 16, 'nombre' => 'La Paz'],
        ['id' => 58, 'provincia_id' => 16, 'nombre' => 'El Alto'],
        ['id' => 59, 'provincia_id' => 16, 'nombre' => 'Palca'],
        ['id' => 60, 'provincia_id' => 16, 'nombre' => 'Achocalla'],
        ['id' => 61, 'provincia_id' => 16, 'nombre' => 'Mecapaca'],
        ['id' => 62, 'provincia_id' => 17, 'nombre' => 'Pucarani'],
        ['id' => 63, 'provincia_id' => 17, 'nombre' => 'Laja'],
        ['id' => 64, 'provincia_id' => 17, 'nombre' => 'Batallas'],
        ['id' => 65, 'provincia_id' => 17, 'nombre' => 'Puerto Pérez'],
        ['id' => 66, 'provincia_id' => 18, 'nombre' => 'Viacha'],
        ['id' => 67, 'provincia_id' => 18, 'nombre' => 'Guaqui'],
        ['id' => 68, 'provincia_id' => 18, 'nombre' => 'Tiahuanacu'],
        ['id' => 69, 'provincia_id' => 18, 'nombre' => 'Desaguadero'],
        ['id' => 70, 'provincia_id' => 18, 'nombre' => 'San Andrés de Machaca'],
        ['id' => 71, 'provincia_id' => 18, 'nombre' => 'Jesús de Machaca'],
        ['id' => 72, 'provincia_id' => 18, 'nombre' => 'Taraco'],
        ['id' => 73, 'provincia_id' => 19, 'nombre' => 'Sica Sica'],
        ['id' => 74, 'provincia_id' => 19, 'nombre' => 'Umala'],
        ['id' => 75, 'provincia_id' => 19, 'nombre' => 'Ayo Ayo'],
        ['id' => 76, 'provincia_id' => 19, 'nombre' => 'Calamarca'],
        ['id' => 77, 'provincia_id' => 19, 'nombre' => 'Patacamaya'],
        ['id' => 78, 'provincia_id' => 19, 'nombre' => 'Colquencha'],
        ['id' => 79, 'provincia_id' => 19, 'nombre' => 'Collana'],
        ['id' => 80, 'provincia_id' => 20, 'nombre' => 'Achacachi'],
        ['id' => 81, 'provincia_id' => 20, 'nombre' => 'Ancoraimes'],
        ['id' => 82, 'provincia_id' => 20, 'nombre' => 'Chua Cocani'],
        ['id' => 83, 'provincia_id' => 20, 'nombre' => 'Huarina'],
        ['id' => 84, 'provincia_id' => 20, 'nombre' => 'Santiago de Huata'],
        ['id' => 85, 'provincia_id' => 20, 'nombre' => 'Huatajata'],
        ['id' => 86, 'provincia_id' => 21, 'nombre' => 'San Pedro de Curahuara'],
        ['id' => 87, 'provincia_id' => 21, 'nombre' => 'Papel Pampa'],
        ['id' => 88, 'provincia_id' => 21, 'nombre' => 'Chacarilla'],
        ['id' => 89, 'provincia_id' => 21, 'nombre' => 'Turco'],
        ['id' => 90, 'provincia_id' => 21, 'nombre' => 'Nazacara'],
        ['id' => 91, 'provincia_id' => 22, 'nombre' => 'Copacabana'],
        ['id' => 92, 'provincia_id' => 22, 'nombre' => 'San Pedro de Tiquina'],
        ['id' => 93, 'provincia_id' => 22, 'nombre' => 'Tito Yupanki'],
        ['id' => 94, 'provincia_id' => 23, 'nombre' => 'Coro Coro'],
        ['id' => 95, 'provincia_id' => 23, 'nombre' => 'Caquiaviri'],
        ['id' => 96, 'provincia_id' => 23, 'nombre' => 'Calacoto'],
        ['id' => 97, 'provincia_id' => 23, 'nombre' => 'Comanche'],
        ['id' => 98, 'provincia_id' => 23, 'nombre' => 'Charaña'],
        ['id' => 99, 'provincia_id' => 23, 'nombre' => 'Waldo Ballivián'],
        ['id' => 100, 'provincia_id' => 23, 'nombre' => 'Nazacara de Pacajes'],
        ['id' => 101, 'provincia_id' => 23, 'nombre' => 'Callapa'],
        ['id' => 102, 'provincia_id' => 23, 'nombre' => 'Santiago de Callapa'],
        ['id' => 103, 'provincia_id' => 24, 'nombre' => 'Coroico'],
        ['id' => 104, 'provincia_id' => 24, 'nombre' => 'Coripata'],
        ['id' => 105, 'provincia_id' => 25, 'nombre' => 'Chulumani'],
        ['id' => 106, 'provincia_id' => 25, 'nombre' => 'Irupana'],
        ['id' => 107, 'provincia_id' => 25, 'nombre' => 'Yanacachi'],
        ['id' => 108, 'provincia_id' => 25, 'nombre' => 'Palos Blancos'],
        ['id' => 109, 'provincia_id' => 25, 'nombre' => 'La Asunta'],
        ['id' => 110, 'provincia_id' => 26, 'nombre' => 'Caranavi'],
        ['id' => 111, 'provincia_id' => 26, 'nombre' => 'Alto Beni'],
        ['id' => 112, 'provincia_id' => 27, 'nombre' => 'Sorata'],
        ['id' => 113, 'provincia_id' => 27, 'nombre' => 'Guanay'],
        ['id' => 114, 'provincia_id' => 27, 'nombre' => 'Tacacoma'],
        ['id' => 115, 'provincia_id' => 27, 'nombre' => 'Quiabaya'],
        ['id' => 116, 'provincia_id' => 27, 'nombre' => 'Combaya'],
        ['id' => 117, 'provincia_id' => 27, 'nombre' => 'Tipuani'],
        ['id' => 118, 'provincia_id' => 27, 'nombre' => 'Mapiri'],
        ['id' => 119, 'provincia_id' => 27, 'nombre' => 'Teoponte'],
        ['id' => 120, 'provincia_id' => 28, 'nombre' => 'Inquisivi'],
        ['id' => 121, 'provincia_id' => 28, 'nombre' => 'Quime'],
        ['id' => 122, 'provincia_id' => 28, 'nombre' => 'Cajuata'],
        ['id' => 123, 'provincia_id' => 28, 'nombre' => 'Colquiri'],
        ['id' => 124, 'provincia_id' => 28, 'nombre' => 'Ichoca'],
        ['id' => 125, 'provincia_id' => 28, 'nombre' => 'Licoma Pampa'],
        ['id' => 126, 'provincia_id' => 28, 'nombre' => 'Viloco'],
        ['id' => 127, 'provincia_id' => 29, 'nombre' => 'Yaco'],
        ['id' => 128, 'provincia_id' => 29, 'nombre' => 'Malla'],
        ['id' => 129, 'provincia_id' => 29, 'nombre' => 'Luribay'],
        ['id' => 130, 'provincia_id' => 29, 'nombre' => 'Sapahaqui'],
        ['id' => 131, 'provincia_id' => 29, 'nombre' => 'Cairoma'],
        ['id' => 132, 'provincia_id' => 29, 'nombre' => 'Caxata'],
        ['id' => 133, 'provincia_id' => 29, 'nombre' => 'Sicasica'],
        ['id' => 134, 'provincia_id' => 29, 'nombre' => 'Salinas'],
        ['id' => 135, 'provincia_id' => 30, 'nombre' => 'Santiago de Machaca'],
        ['id' => 136, 'provincia_id' => 30, 'nombre' => 'Catacora'],
        ['id' => 137, 'provincia_id' => 31, 'nombre' => 'Chuma'],
        ['id' => 138, 'provincia_id' => 31, 'nombre' => 'Ayata'],
        ['id' => 139, 'provincia_id' => 31, 'nombre' => 'Aucapata'],
        ['id' => 140, 'provincia_id' => 32, 'nombre' => 'Puerto Acosta'],
        ['id' => 141, 'provincia_id' => 32, 'nombre' => 'Mocomoco'],
        ['id' => 142, 'provincia_id' => 32, 'nombre' => 'Puerto Carabuco'],
        ['id' => 143, 'provincia_id' => 32, 'nombre' => 'Humanata'],
        ['id' => 144, 'provincia_id' => 32, 'nombre' => 'Escoma'],
        ['id' => 145, 'provincia_id' => 33, 'nombre' => 'Charazani'],
        ['id' => 146, 'provincia_id' => 33, 'nombre' => 'Curva'],
        ['id' => 147, 'provincia_id' => 34, 'nombre' => 'Apolo'],
        ['id' => 148, 'provincia_id' => 34, 'nombre' => 'Pelechuco'],
        ['id' => 149, 'provincia_id' => 35, 'nombre' => 'Ixiamas'],
        ['id' => 150, 'provincia_id' => 35, 'nombre' => 'San Buenaventura'],
        ['id' => 151, 'provincia_id' => 36, 'nombre' => 'Cochabamba'],
        ['id' => 152, 'provincia_id' => 37, 'nombre' => 'Quillacollo'],
        ['id' => 153, 'provincia_id' => 37, 'nombre' => 'Colcapirhua'],
        ['id' => 154, 'provincia_id' => 37, 'nombre' => 'Tiquipaya'],
        ['id' => 155, 'provincia_id' => 37, 'nombre' => 'Vinto'],
        ['id' => 156, 'provincia_id' => 37, 'nombre' => 'Sipe Sipe'],
        ['id' => 157, 'provincia_id' => 37, 'nombre' => 'Sacaba'],
        ['id' => 158, 'provincia_id' => 38, 'nombre' => 'Villa Tunari'],
        ['id' => 159, 'provincia_id' => 38, 'nombre' => 'Shinahota'],
        ['id' => 160, 'provincia_id' => 38, 'nombre' => 'Entre Ríos'],
        ['id' => 161, 'provincia_id' => 38, 'nombre' => 'Puerto Villarroel'],
        ['id' => 162, 'provincia_id' => 39, 'nombre' => 'Punata'],
        ['id' => 163, 'provincia_id' => 39, 'nombre' => 'Villa Rivero'],
        ['id' => 164, 'provincia_id' => 39, 'nombre' => 'San Benito'],
        ['id' => 165, 'provincia_id' => 39, 'nombre' => 'Tacachi'],
        ['id' => 166, 'provincia_id' => 39, 'nombre' => 'Cuchumuela'],
        ['id' => 167, 'provincia_id' => 39, 'nombre' => 'Villa Gualberto Villarroel'],
        ['id' => 168, 'provincia_id' => 40, 'nombre' => 'Tapacari'],
        ['id' => 169, 'provincia_id' => 41, 'nombre' => 'Tarata'],
        ['id' => 170, 'provincia_id' => 41, 'nombre' => 'Anzaldo'],
        ['id' => 171, 'provincia_id' => 41, 'nombre' => 'Arbieto'],
        ['id' => 172, 'provincia_id' => 41, 'nombre' => 'Sacabamba'],
        ['id' => 173, 'provincia_id' => 42, 'nombre' => 'Arani'],
        ['id' => 174, 'provincia_id' => 42, 'nombre' => 'Vacas'],
        ['id' => 175, 'provincia_id' => 43, 'nombre' => 'Ayopaya'],
        ['id' => 176, 'provincia_id' => 43, 'nombre' => 'Independencia'],
        ['id' => 177, 'provincia_id' => 43, 'nombre' => 'Morochata'],
        ['id' => 178, 'provincia_id' => 43, 'nombre' => 'Cocapata'],
        ['id' => 179, 'provincia_id' => 44, 'nombre' => 'Capinota'],
        ['id' => 180, 'provincia_id' => 44, 'nombre' => 'Santiváñez'],
        ['id' => 181, 'provincia_id' => 44, 'nombre' => 'Sicaya'],
        ['id' => 182, 'provincia_id' => 45, 'nombre' => 'Totora'],
        ['id' => 183, 'provincia_id' => 45, 'nombre' => 'Pojo'],
        ['id' => 184, 'provincia_id' => 45, 'nombre' => 'Pocona'],
        ['id' => 185, 'provincia_id' => 45, 'nombre' => 'Chimoré'],
        ['id' => 186, 'provincia_id' => 46, 'nombre' => 'Bolívar'],
        ['id' => 187, 'provincia_id' => 46, 'nombre' => 'San Pedro de Buena Vista'],
        ['id' => 188, 'provincia_id' => 47, 'nombre' => 'Mizque'],
        ['id' => 189, 'provincia_id' => 47, 'nombre' => 'Vila Vila'],
        ['id' => 190, 'provincia_id' => 47, 'nombre' => 'Alalay'],
        ['id' => 191, 'provincia_id' => 48, 'nombre' => 'Aiquile'],
        ['id' => 192, 'provincia_id' => 48, 'nombre' => 'Omereque'],
        ['id' => 193, 'provincia_id' => 48, 'nombre' => 'Pasorapa'],
        ['id' => 194, 'provincia_id' => 49, 'nombre' => 'Tiraque'],
        ['id' => 195, 'provincia_id' => 50, 'nombre' => 'Cliza'],
        ['id' => 196, 'provincia_id' => 50, 'nombre' => 'Toco'],
        ['id' => 197, 'provincia_id' => 50, 'nombre' => 'Tolata'],
        ['id' => 198, 'provincia_id' => 51, 'nombre' => 'Arque'],
        ['id' => 199, 'provincia_id' => 51, 'nombre' => 'Tacopaya'],
        ['id' => 200, 'provincia_id' => 52, 'nombre' => 'Potosí'],
        ['id' => 201, 'provincia_id' => 52, 'nombre' => 'Tinguipaya'],
        ['id' => 202, 'provincia_id' => 52, 'nombre' => 'Urmiri'],
        ['id' => 203, 'provincia_id' => 52, 'nombre' => 'Yocalla'],
        ['id' => 204, 'provincia_id' => 53, 'nombre' => 'Cotagaita'],
        ['id' => 205, 'provincia_id' => 53, 'nombre' => 'Vitichi'],
        ['id' => 206, 'provincia_id' => 53, 'nombre' => 'Sagrario'],
        ['id' => 207, 'provincia_id' => 53, 'nombre' => 'Tacachira'],
        ['id' => 208, 'provincia_id' => 54, 'nombre' => 'Villazón'],
        ['id' => 209, 'provincia_id' => 55, 'nombre' => 'San Agustín'],
        ['id' => 210, 'provincia_id' => 56, 'nombre' => 'Uncía'],
        ['id' => 211, 'provincia_id' => 56, 'nombre' => 'Chayanta'],
        ['id' => 212, 'provincia_id' => 56, 'nombre' => 'Llallagua'],
        ['id' => 213, 'provincia_id' => 56, 'nombre' => 'Chuquihuta'],
        ['id' => 214, 'provincia_id' => 57, 'nombre' => 'Uyuni'],
        ['id' => 215, 'provincia_id' => 57, 'nombre' => 'Tomave'],
        ['id' => 216, 'provincia_id' => 57, 'nombre' => 'Porco'],
        ['id' => 217, 'provincia_id' => 58, 'nombre' => 'Tupiza'],
        ['id' => 218, 'provincia_id' => 58, 'nombre' => 'Atocha'],
        ['id' => 219, 'provincia_id' => 58, 'nombre' => 'Esmoraca'],
        ['id' => 220, 'provincia_id' => 58, 'nombre' => 'Mojinete'],
        ['id' => 221, 'provincia_id' => 58, 'nombre' => 'San Pablo de Lípez'],
        ['id' => 222, 'provincia_id' => 59, 'nombre' => 'Betanzos'],
        ['id' => 223, 'provincia_id' => 59, 'nombre' => 'Chaquí'],
        ['id' => 224, 'provincia_id' => 59, 'nombre' => 'Tacobamba'],
        ['id' => 225, 'provincia_id' => 60, 'nombre' => 'Puna'],
        ['id' => 226, 'provincia_id' => 60, 'nombre' => 'Caiza D'],
        ['id' => 227, 'provincia_id' => 60, 'nombre' => 'Ckochas'],
        ['id' => 228, 'provincia_id' => 61, 'nombre' => 'San Pedro de Buena Vista'],
        ['id' => 229, 'provincia_id' => 61, 'nombre' => 'Toro Toro'],
        ['id' => 230, 'provincia_id' => 62, 'nombre' => 'Colquechaca'],
        ['id' => 231, 'provincia_id' => 62, 'nombre' => 'Pocoata'],
        ['id' => 232, 'provincia_id' => 62, 'nombre' => 'Ravelo'],
        ['id' => 233, 'provincia_id' => 62, 'nombre' => 'Ocurí'],
        ['id' => 234, 'provincia_id' => 62, 'nombre' => 'Surihaya'],
        ['id' => 235, 'provincia_id' => 63, 'nombre' => 'Colcha K'],
        ['id' => 236, 'provincia_id' => 63, 'nombre' => 'San Pedro de Quemes'],
        ['id' => 237, 'provincia_id' => 63, 'nombre' => 'Llica'],
        ['id' => 238, 'provincia_id' => 64, 'nombre' => 'San Pablo de Lípez'],
        ['id' => 239, 'provincia_id' => 64, 'nombre' => 'San Antonio de Esmoruco'],
        ['id' => 240, 'provincia_id' => 65, 'nombre' => 'Sacaca'],
        ['id' => 241, 'provincia_id' => 65, 'nombre' => 'Caripuyo'],
        ['id' => 242, 'provincia_id' => 66, 'nombre' => 'Arampampa'],
        ['id' => 243, 'provincia_id' => 66, 'nombre' => 'Acasio'],
        ['id' => 244, 'provincia_id' => 67, 'nombre' => 'Llica'],
        ['id' => 245, 'provincia_id' => 67, 'nombre' => 'Tahua'],
        ['id' => 246, 'provincia_id' => 68, 'nombre' => 'Sucre'],
        ['id' => 247, 'provincia_id' => 68, 'nombre' => 'Yotala'],
        ['id' => 248, 'provincia_id' => 68, 'nombre' => 'Poroma'],
        ['id' => 249, 'provincia_id' => 69, 'nombre' => 'Padilla'],
        ['id' => 250, 'provincia_id' => 69, 'nombre' => 'Tomina'],
        ['id' => 251, 'provincia_id' => 69, 'nombre' => 'Sopachuy'],
        ['id' => 252, 'provincia_id' => 69, 'nombre' => 'Villa Alcalá'],
        ['id' => 253, 'provincia_id' => 69, 'nombre' => 'El Villar'],
        ['id' => 254, 'provincia_id' => 69, 'nombre' => 'Monteagudo'],
        ['id' => 255, 'provincia_id' => 70, 'nombre' => 'Azurduy'],
        ['id' => 256, 'provincia_id' => 70, 'nombre' => 'Tarvita'],
        ['id' => 257, 'provincia_id' => 71, 'nombre' => 'Villa Zudáñez'],
        ['id' => 258, 'provincia_id' => 71, 'nombre' => 'Presto'],
        ['id' => 259, 'provincia_id' => 71, 'nombre' => 'Mojocoya'],
        ['id' => 260, 'provincia_id' => 71, 'nombre' => 'Icla'],
        ['id' => 261, 'provincia_id' => 72, 'nombre' => 'Tarabuco'],
        ['id' => 262, 'provincia_id' => 72, 'nombre' => 'Yamparáez'],
        ['id' => 263, 'provincia_id' => 73, 'nombre' => 'Monteagudo'],
        ['id' => 264, 'provincia_id' => 73, 'nombre' => 'Huacareta'],
        ['id' => 265, 'provincia_id' => 73, 'nombre' => 'Macharetí'],
        ['id' => 266, 'provincia_id' => 73, 'nombre' => 'Villa Vaca Guzmán'],
        ['id' => 267, 'provincia_id' => 74, 'nombre' => 'Camargo'],
        ['id' => 268, 'provincia_id' => 74, 'nombre' => 'San Lucas'],
        ['id' => 269, 'provincia_id' => 74, 'nombre' => 'Incahuasi'],
        ['id' => 270, 'provincia_id' => 74, 'nombre' => 'Villa Charcas'],
        ['id' => 271, 'provincia_id' => 75, 'nombre' => 'Villa Abecia'],
        ['id' => 272, 'provincia_id' => 75, 'nombre' => 'Culpina'],
        ['id' => 273, 'provincia_id' => 75, 'nombre' => 'Las Carreras'],
        ['id' => 274, 'provincia_id' => 75, 'nombre' => 'Camataquí'],
        ['id' => 275, 'provincia_id' => 76, 'nombre' => 'Villa Serrano'],
        ['id' => 276, 'provincia_id' => 76, 'nombre' => 'Las Carreras'],
        ['id' => 277, 'provincia_id' => 77, 'nombre' => 'Villa Vaca Guzmán'],
        ['id' => 278, 'provincia_id' => 77, 'nombre' => 'Huacaya'],
        ['id' => 279, 'provincia_id' => 77, 'nombre' => 'Macharetí'],
        ['id' => 280, 'provincia_id' => 77, 'nombre' => 'Boyuibe'],
        ['id' => 281, 'provincia_id' => 78, 'nombre' => 'Oruro'],
        ['id' => 282, 'provincia_id' => 78, 'nombre' => 'Caracollo'],
        ['id' => 283, 'provincia_id' => 78, 'nombre' => 'El Choro'],
        ['id' => 284, 'provincia_id' => 78, 'nombre' => 'Soracachi'],
        ['id' => 285, 'provincia_id' => 79, 'nombre' => 'Poopó'],
        ['id' => 286, 'provincia_id' => 79, 'nombre' => 'Pazña'],
        ['id' => 287, 'provincia_id' => 79, 'nombre' => 'Antequera'],
        ['id' => 288, 'provincia_id' => 79, 'nombre' => 'Puna'],
        ['id' => 289, 'provincia_id' => 80, 'nombre' => 'Huanuni'],
        ['id' => 290, 'provincia_id' => 80, 'nombre' => 'Machacamarca'],
        ['id' => 291, 'provincia_id' => 81, 'nombre' => 'Toledo'],
        ['id' => 292, 'provincia_id' => 81, 'nombre' => 'Santiago de Huari'],
        ['id' => 293, 'provincia_id' => 82, 'nombre' => 'Santiago de Huari'],
        ['id' => 294, 'provincia_id' => 82, 'nombre' => 'Santuario de Quillacas'],
        ['id' => 295, 'provincia_id' => 83, 'nombre' => 'Eucaliptus'],
        ['id' => 296, 'provincia_id' => 83, 'nombre' => 'La Rivera'],
        ['id' => 297, 'provincia_id' => 84, 'nombre' => 'La Rivera'],
        ['id' => 298, 'provincia_id' => 84, 'nombre' => 'Todos Santos'],
        ['id' => 299, 'provincia_id' => 84, 'nombre' => 'Esmeralda'],
        ['id' => 300, 'provincia_id' => 85, 'nombre' => 'Totora'],
        ['id' => 301, 'provincia_id' => 86, 'nombre' => 'Cruz de Machacamarca'],
        ['id' => 302, 'provincia_id' => 86, 'nombre' => 'Esmeralda'],
        ['id' => 303, 'provincia_id' => 86, 'nombre' => 'Eucaliptus'],
        ['id' => 304, 'provincia_id' => 87, 'nombre' => 'Challapata'],
        ['id' => 305, 'provincia_id' => 87, 'nombre' => 'Quillacas'],
        ['id' => 306, 'provincia_id' => 87, 'nombre' => 'Santuario de Quillacas'],
        ['id' => 307, 'provincia_id' => 88, 'nombre' => 'Huachacalla'],
        ['id' => 308, 'provincia_id' => 89, 'nombre' => 'Andamarca'],
        ['id' => 309, 'provincia_id' => 89, 'nombre' => 'Belén de Andamarca'],
        ['id' => 310, 'provincia_id' => 90, 'nombre' => 'Corque'],
        ['id' => 311, 'provincia_id' => 90, 'nombre' => 'Choque Cota'],
        ['id' => 312, 'provincia_id' => 91, 'nombre' => 'Curahuara de Carangas'],
        ['id' => 313, 'provincia_id' => 91, 'nombre' => 'Turco'],
        ['id' => 314, 'provincia_id' => 92, 'nombre' => 'Salinas de Garci Mendoza'],
        ['id' => 315, 'provincia_id' => 93, 'nombre' => 'Sabaya'],
        ['id' => 316, 'provincia_id' => 93, 'nombre' => 'Coipasa'],
        ['id' => 317, 'provincia_id' => 93, 'nombre' => 'Chipaya'],
        ['id' => 318, 'provincia_id' => 94, 'nombre' => 'Tarija'],
        ['id' => 319, 'provincia_id' => 94, 'nombre' => 'Uriondo'],
        ['id' => 320, 'provincia_id' => 94, 'nombre' => 'Yunchará'],
        ['id' => 321, 'provincia_id' => 95, 'nombre' => 'San Lorenzo'],
        ['id' => 322, 'provincia_id' => 95, 'nombre' => 'El Puente'],
        ['id' => 323, 'provincia_id' => 96, 'nombre' => 'Yunchará'],
        ['id' => 324, 'provincia_id' => 96, 'nombre' => 'Iscayachi'],
        ['id' => 325, 'provincia_id' => 97, 'nombre' => 'Padcaya'],
        ['id' => 326, 'provincia_id' => 97, 'nombre' => 'Bermejo'],
        ['id' => 327, 'provincia_id' => 97, 'nombre' => 'Entre Ríos'],
        ['id' => 328, 'provincia_id' => 98, 'nombre' => 'Villa Montes'],
        ['id' => 329, 'provincia_id' => 99, 'nombre' => 'Yacuiba'],
        ['id' => 330, 'provincia_id' => 99, 'nombre' => 'Caraparí'],
        ['id' => 331, 'provincia_id' => 99, 'nombre' => 'Villa Montes'],
        ['id' => 332, 'provincia_id' => 100, 'nombre' => 'Trinidad'],
        ['id' => 333, 'provincia_id' => 100, 'nombre' => 'San Javier'],
        ['id' => 334, 'provincia_id' => 101, 'nombre' => 'Santa Ana del Yacuma'],
        ['id' => 335, 'provincia_id' => 101, 'nombre' => 'Exaltación'],
        ['id' => 336, 'provincia_id' => 102, 'nombre' => 'Riberalta'],
        ['id' => 337, 'provincia_id' => 102, 'nombre' => 'Guayaramerín'],
        ['id' => 338, 'provincia_id' => 103, 'nombre' => 'San Joaquín'],
        ['id' => 339, 'provincia_id' => 103, 'nombre' => 'San Ramón'],
        ['id' => 340, 'provincia_id' => 103, 'nombre' => 'Puerto Siles'],
        ['id' => 341, 'provincia_id' => 104, 'nombre' => 'San Ignacio'],
        ['id' => 342, 'provincia_id' => 104, 'nombre' => 'San Javier'],
        ['id' => 343, 'provincia_id' => 105, 'nombre' => 'Loreto'],
        ['id' => 344, 'provincia_id' => 105, 'nombre' => 'San Andrés'],
        ['id' => 345, 'provincia_id' => 106, 'nombre' => 'Rurrenabaque'],
        ['id' => 346, 'provincia_id' => 106, 'nombre' => 'Reyes'],
        ['id' => 347, 'provincia_id' => 106, 'nombre' => 'San Borja'],
        ['id' => 348, 'provincia_id' => 106, 'nombre' => 'Santa Rosa'],
        ['id' => 349, 'provincia_id' => 107, 'nombre' => 'Magdalena'],
        ['id' => 350, 'provincia_id' => 107, 'nombre' => 'Baures'],
        ['id' => 351, 'provincia_id' => 107, 'nombre' => 'Huacaraje'],
        ['id' => 352, 'provincia_id' => 108, 'nombre' => 'Cobija'],
        ['id' => 353, 'provincia_id' => 108, 'nombre' => 'Porvenir'],
        ['id' => 354, 'provincia_id' => 108, 'nombre' => 'Filadelfia'],
        ['id' => 355, 'provincia_id' => 108, 'nombre' => 'Bella Flor'],
        ['id' => 356, 'provincia_id' => 108, 'nombre' => 'Bolpebra'],
        ['id' => 357, 'provincia_id' => 109, 'nombre' => 'Puerto Rico'],
        ['id' => 358, 'provincia_id' => 109, 'nombre' => 'San Pedro'],
        ['id' => 359, 'provincia_id' => 110, 'nombre' => 'Puerto Gonzalo Moreno'],
        ['id' => 360, 'provincia_id' => 110, 'nombre' => 'El Sena'],
        ['id' => 361, 'provincia_id' => 111, 'nombre' => 'Nueva Esperanza'],
        ['id' => 362, 'provincia_id' => 111, 'nombre' => 'Villa Nueva'],
        ['id' => 363, 'provincia_id' => 111, 'nombre' => 'Santos Mercado'],
        ['id' => 364, 'provincia_id' => 112, 'nombre' => 'Ingavi'],
        ['id' => 365, 'provincia_id' => 112, 'nombre' => 'Nueva Esperanza'],
    ];
}
